### PR TITLE
Pim16aap2 armored elytra support

### PR DESCRIPTION
**Pull request by bonn2**
This would add support for ArmoredElytras created with [pim16aap2's spigot plugin](https://www.spigotmc.org/resources/armored-elytra.47136/)

### CODE REVIEW

**Comment by mrmelon54** [comment]
I'll take a look at this later

**Comment by mrmelon54** [comment]
Golden and chainmail armour don't display correctly I'm assuming you just got those two muddled? Also I'm going to assume coloured leather support is impossible due to the way the data is stored (or not stored hence why there is no support for it).

**Comment by mrmelon54** [comment]
Let me know when you are done making changes and I'll review the PR again

**Comment by bonn2** [comment]
Color has the support built in for when the plugin updates. (I Built this in conjunction with it's author, so it should start working when that update is released)
Golden and Chainmail are displaying correctly on my side so I'm not sure what is happening there

**Comment by bonn2** [comment]
Here is the copy of armoredelytra that I was testing with
[ArmoredElytra-testbuild.zip](https://github.com/MrMelon54/armored-elytra-fabric-1.16/files/6501860/ArmoredElytra-testbuild.zip)

**Comment by bonn2** [comment]
Hmm seems they are swapped due to a discrepancy between 2.4.14 of AE and the latest 3.0dev series on github

**Comment by mrmelon54** [comment]
The test build you provided doesn't even work for me (testing on paper 1.16.5)

**Comment by bonn2** [comment]
did you unzip it? Github doesn't let you upload .jars

**Comment by mrmelon54** [comment]
It is detected by the server (aka it displays in /plugins) but putting a chestplate and elytra in an anvil doesn't do anything?

**Comment by bonn2** [comment]
oh the 3.0 series also changes the default craft block to the smithing table. Toggle-able in config ofc, but that is probably it

**Comment by mrmelon54** [comment]
image
Golden and chainmail armour still appear swapped but everything else (including coloured leather) appears to work fine

**Comment by bonn2** [comment]
are those made new in that version?
The issue is that the plugin stores a diff value in the items than it should

**Comment by bonn2** [comment]
wait, hmm
This wasn't happening last night lol

**Comment by mrmelon54** [comment]
image
I am using the latest version of the code on your branch and I am using the test build for the plugin that you provided

**Comment by mrmelon54** [comment]
You can probably just swap the values in the switch case for `armor_tier_level`

**Comment by bonn2** [comment]
yeah that will fix it, I am just impressed I missed that. Since I know *for a fact* that I tested that at some point and it worked lol

**Comment by bonn2** [comment]
Also turns out, no 2.4.14 of AE doesn't have an issue I did somehow just get them flipped

**Comment by bonn2** [comment]
image

**Comment by mrmelon54** [comment]
I can confirm this does work as intended

**Comment by mrmelon54** [comment]
Is the new version of the spigot plugin going to be called 3.0?

**Comment by bonn2** [comment]
Yes

**Comment by mrmelon54** [comment]
Curseforge release for v1.0.8 is awaiting approval

**Pull request merged**
